# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
variables:
- group: veracode

schedules:
- cron: "0 9 * * *"
  displayName: "Daily at 9am" 
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

steps:
- bash: |
    pip install -r requirements.txt
    export VERACODE_API_KEY_ID="$(veracode_api_key_id)"
    export VERACODE_API_KEY_SECRET="$(veracode_api_key_secret)"
    export CHANNEL="\$(teams_channel)"
    export TEAMID="\$(teamid)"
    python3 veracode_get_user_list.py --team --kwargs teamid="\$TEAMID” channel="\$CHANNEL”
  displayName: 'Run a multi-line script'
