# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    python3 veracode_get_user_list.py --team --kwargs teamid=d36c3d0d-d002-48ea-8063-a8b6e24a98fa
  displayName: 'Run a multi-line script'
