variables:
- group: veracode

# YAML file in the main branch
schedules:
- cron: "0 9 * * *"
  displayName: Daily 9:00 AM  build
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

steps:
- script: pip install -r requirements.txt
  displayName: 'Install python requirements'
- bash: |
    export VERACODE_API_KEY_ID=$(veracode_api_key_id)
    export VERACODE_API_KEY_SECRET=$(veracode_api_key_secret)
    python3 veracode_get_user_list.py --teamid $(teamid) --channel "$(teams_channel)""
  displayName: 'Request default team members'
